[package]
name = "coap_server"
version = "0.1.0"
edition = "2021"

[dependencies]
libcoap-rs = { version = "0.2.2", path = "../libcoap-rs/libcoap" }
libcoap-sys = { version = "0.2.2", path = "../libcoap-rs/libcoap-sys" }

